//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaodienQLQuanTS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int Id { get; set; }
        public int SoHD { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public double ThanhTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
